[MP-2565] add support for mysql
UNIwise/parrot pull request #61
Opened 2024-08-19 14:11 UTC by IslamMonjid

### What this pull request does
add support for mysql

[MP-2565](https://uniwise.atlassian.net/browse/MP-2565)

2024-08-19 20:36 UTC, Graloth requested changes
To fix the failing build/test, add the following to the `.dockerignore` file:
```
!migrations
```

Otherwise they are not included during the container image build process.

2024-08-20 08:36 UTC, Sebsh1 approved these changes

2024-08-20 12:30 UTC, Graloth approved these changes

2024-08-20 13:17 UTC, nikolai-str approved these changes

2024-08-20 16:04 UTC, merged